name: Build and Push Docker Image

on:
  push:
  workflow_dispatch:
    inputs:
      core_branch:
        description: 'Branch core'
        required: false
        default: 'fork'
        type: string
      sdkjs_branch:
        description: 'Branch for sdkjs'
        required: false
        default: 'fork'
        type: string
      web_apps_branch:
        description: 'Branch for web-apps'
        required: false
        default: 'fork'
        type: string
      server_branch:
        description: 'Branch for server'
        required: false
        default: 'fork'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: euro-office/documentserver
  PRODUCT_VERSION: 9.2.1
  BUILD_ROOT: /package
  #CHECKOUT_REF: ${{ github.event.inputs.ref || 'fork' }}

jobs:
  clone:
    runs-on: self-hosted
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          path: fork/

      - name: Checkout core
        uses: actions/checkout@v6
        with:
          repository: euro-office/core
          path: core/
          ref: ${{ github.event.inputs.core_branch || 'fork' }}
          token: ${{ secrets.EURO_OFFICE_MIRROR_TOKEN }}
          fetch-depth: 0

      - name: Checkout core-fonts
        uses: actions/checkout@v6
        with:
          repository: euro-office/core-fonts
          path: core-fonts/
          ref: ${{ env.CHECKOUT_REF }}
          token: ${{ secrets.EURO_OFFICE_MIRROR_TOKEN }}

      - name: Checkout sdkjs-plugins
        uses: actions/checkout@v6
        if: false
        with:
          repository: euro-office/onlyoffice.github.io
          path: onlyoffice.github.io/
          ref: master
          token: ${{ secrets.EURO_OFFICE_MIRROR_TOKEN }}

      - name: Checkout sdkjs
        uses: actions/checkout@v6
        with:
          repository: euro-office/sdkjs
          path: sdkjs/
          ref: ${{ github.event.inputs.sdkjs_branch || 'fork' }}
          token: ${{ secrets.EURO_OFFICE_MIRROR_TOKEN }}

      - name: Checkout web-apps
        uses: actions/checkout@v6
        with:
          repository: euro-office/web-apps
          path: web-apps/
          ref: ${{ github.event.inputs.web_apps_branch || 'fork' }}
          token: ${{ secrets.EURO_OFFICE_MIRROR_TOKEN }}

      - name: Checkout server
        uses: actions/checkout@v6
        with:
          repository: euro-office/server
          path: server/
          ref: ${{ github.event.inputs.server_branch || 'fork' }}
          token: ${{ secrets.EURO_OFFICE_MIRROR_TOKEN }}

      - name: Cache clones
        uses: actions/cache@v4
        with:
          path: "${{ github.workspace }}"
          key: ${{ runner.os }}-build-${{ github.sha }}

  build:
    runs-on: self-hosted
    needs: clone
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - core
          - sdkjs
          - web-apps
          - server

    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: "${{ github.workspace }}"
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-${{ matrix.target }}-
            type=raw,value=${{ matrix.target }}-stage
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./fork/build/Dockerfile
          target: ${{ matrix.target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PRODUCT_VERSION=${{ env.PRODUCT_VERSION }}
            BUILD_ROOT=${{ env.BUILD_ROOT }}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.target }}-buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.target }}-buildcache,mode=max


  combine:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: "${{ github.workspace }}"
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./fork/build/Dockerfile
          target: finalubuntu
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PRODUCT_VERSION=${{ env.PRODUCT_VERSION }}
            BUILD_ROOT=${{ env.BUILD_ROOT }}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:core-buildcache
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sdkjs-buildcache
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:web-apps-buildcache
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:server-buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:final-buildcache,mode=max


  build-develop:
    runs-on: self-hosted
    needs: combine
    permissions:
      contents: read
      packages: write

    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: "${{ github.workspace }}"
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-develop-
            type=raw,value=develop-stage
            type=raw,value=latest-dev,enable={{is_default_branch}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./fork/build/Dockerfile
          target: develop
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            PRODUCT_VERSION=${{ env.PRODUCT_VERSION }}
            BUILD_ROOT=${{ env.BUILD_ROOT }}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:final-buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-buildcache,mode=max