name: Mirror upstream repositories

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 05 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - build_tools
          - core
          - core-fonts
          - DesktopEditors
          - desktop-apps
          - desktop-sdk
          - dictionaries
          - Docker-DocumentServer
          - document-server-integration
          - document-server-package
          - document-templates
          - onlyoffice.github.io
          - sdkjs
          - sdkjs-forms
          - server
          - web-apps

    steps:
    - name: Checkout runner workspace
      run: |
        mkdir -p tmp-repo
        cd tmp-repo
        git config --global user.name "Euro-Office via GitHub Actions"
        git clone --bare https://github.com/ONLYOFFICE/${{ matrix.repo }}.git
        cd ${{ matrix.repo }}.git
        git fetch --all
        git remote add eurooffice https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/Euro-Office/${{ matrix.repo }}.git
        # Push all branches and tags from the cloned bare repository to the eurooffice remote.
        # Avoid --mirror because it can delete branches on the target that exist only there.
        git push eurooffice --all --force-with-lease
        git push eurooffice --tags --force-with-lease
      env:
        GITHUB_TOKEN: ${{ secrets.EURO_OFFICE_MIRROR_TOKEN }}
